In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("superstore_orders.csv",encoding='latin')
df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [3]:
# the total profit of all the sales

df['Profit'].sum()

1312442.3994236002

In [4]:
# The profit by each region

df.groupby('Region')['Profit'].sum()

Region
Central    519825.567066
East       377566.186045
South      104201.192421
West       310849.453891
Name: Profit, dtype: float64

In [5]:
df.groupby('State or Province')['Profit'].sum()

State or Province
Alabama                  10771.983920
Arizona                  43506.286360
Arkansas                  9433.202520
California               86098.387760
Colorado                 20058.021744
Connecticut               7557.108486
Delaware                    63.934640
District of Columbia     25515.488720
Florida                  24416.807245
Georgia                  15573.853705
Idaho                    15660.122920
Illinois                127840.023010
Indiana                  36401.278912
Iowa                     17070.291878
Kansas                   15000.668400
Kentucky                  8129.198488
Louisiana                  937.355728
Maine                    16509.323371
Maryland                 21043.770734
Massachusetts            42856.248113
Michigan                 53041.351644
Minnesota                33603.852099
Mississippi             -18044.540005
Missouri                 24628.870918
Montana                  -9463.687970
Nebraska                 10257.582140
Nevada                    4395.281716
New Hampshire            10300.497911
New Jersey               24735.765274
New Mexico               26011.011684
New York                113558.974853
North Carolina           26620.893697
North Dakota              8853.765680
Ohio                     69609.273145
Oklahoma                 25436.070772
Oregon                   54303.005068
Pennsylvania             27206.996256
Rhode Island              6624.701320
South Carolina             663.384467
South Dakota             17903.090120
Tennessee                -6902.007830
Texas                   109005.260814
Utah                     18440.843872
Vermont                   7990.110591
Virginia                 32601.060488
Washington               45329.262557
West Virginia             3993.992629
Wisconsin                40783.460680
Wyoming                   6510.918180
Name: Profit, dtype: float64

In [11]:
#df.pivot_table(index='State or Province', columns='Region', values='Profit',aggfunc='sum')

In [12]:
#df.pivot_table(index=['Region','State or Province'], columns= 'Customer Segment', values='Row ID',aggfunc='count')
df.pivot_table(index=['Region','State or Province'], values='Profit',aggfunc='sum')
#index is for what u wanna see on ur x-axis
#values is what u wanna see
#aggfunc gives what data u want displayed. can change to count, sum etc

                                     Profit
Region  State or Province
Central Illinois              127840.023010
        Indiana                36401.278912
        Iowa                   17070.291878
        Kansas                 15000.668400
        Michigan               53041.351644
        Minnesota              33603.852099
        Missouri               24628.870918
        Nebraska               10257.582140
        North Dakota            8853.765680
        Oklahoma               25436.070772
        South Dakota           17903.090120
        Texas                 109005.260814
        Wisconsin              40783.460680
East    Connecticut             7557.108486
        Delaware                  63.934640
        District of Columbia   25515.488720
        Maine                  16509.323371
        Maryland               21043.770734
        Massachusetts          42856.248113
        New Hampshire          10300.497911
        New Jersey             24735.765274
        New York              113558.974853
        Ohio                   69609.273145
        Pennsylvania           27206.996256
        Rhode Island            6624.701320
        Vermont                 7990.110591
        West Virginia           3993.992629
South   Alabama                10771.983920
        Arkansas                9433.202520
        Florida                24416.807245
        Georgia                15573.853705
        Kentucky                8129.198488
        Louisiana                937.355728
        Mississippi           -18044.540005
        North Carolina         26620.893697
        South Carolina           663.384467
        Tennessee              -6902.007830
        Virginia               32601.060488
West    Arizona                43506.286360
        California             86098.387760
        Colorado               20058.021744
        Idaho                  15660.122920
        Montana                -9463.687970
        Nevada                  4395.281716
        New Mexico             26011.011684
        Oregon                 54303.005068
        Utah                   18440.843872
        Washington             45329.262557
        Wyoming                 6510.918180

In [15]:
salesByCities = df.pivot_table(index=['Region','State or Province', 'City'], values='Profit',aggfunc='sum')

In [17]:
salesByCities.head(10)

                                                  Profit
Region  State or Province City
Central Illinois          Addison              25.471260
                          Alton              1063.890380
                          Arlington Heights   -69.900852
                          Aurora             1276.412920
                          Batavia             170.609320
                          Belleville          992.362100
                          Belvidere          -369.961500
                          Bloomington        -950.710980
                          Bolingbrook        -495.713200
                          Buffalo Grove      2187.203500

In [18]:
salesByCities['Profit']

Region   State or Province  City
Central  Illinois           Addison                25.471260
                            Alton                1063.890380
                            Arlington Heights     -69.900852
                            Aurora               1276.412920
                            Batavia               170.609320
                                                    ...
West     Wyoming            Casper               2153.901200
                            Cheyenne              451.865300
                            Gillette             3374.465500
                            Laramie               368.818500
                            Rock Springs          161.867680
Name: Profit, Length: 1619, dtype: float64

In [20]:
df1 = df.pivot_table(index=['Region','State or Province'], columns ='Product Category', values='Profit',aggfunc='sum')
df1
#profit is now divided by columns (Product Category)

Product Category                 Furniture  Office Supplies    Technology
Region  State or Province
Central Illinois              20277.222916     43136.533480  64426.266614
        Indiana               12643.131611     13459.832672  10298.314629
        Iowa                  -1457.577960      9478.542350   9049.327488
        Kansas                 2999.125680      4647.956340   7353.586380
        Michigan                894.250848     14907.553124  37239.547672
        Minnesota             -3294.794604      4448.651800  32449.994903
        Missouri              -4951.756520     14372.644292  15207.983146
        Nebraska                952.957120      6802.814740   2501.810280
        North Dakota           2584.768800      4677.715080   1591.281800
        Oklahoma               8681.608400       466.522684  16287.939688
        South Dakota           2059.465120      2602.251300  13241.373700
        Texas                  8948.375098     39283.983044  60772.902672
        Wisconsin              4884.728504      8899.930696  26998.801480
East    Connecticut               3.825791      3592.215124   3961.067571
        Delaware                423.498900       232.765400   -592.329660
        District of Columbia   4726.279220     14503.705800   6285.503700
        Maine                  1131.760551      3918.059580  11459.503240
        Maryland               9867.508702      5548.200896   5628.061136
        Massachusetts          7113.471195     10565.320024  25177.456894
        New Hampshire          3032.876471      2717.263440   4550.358000
        New Jersey            -7188.094954      9610.491928  22313.368300
        New York               2131.313209     30316.796462  81110.865182
        Ohio                   4879.188759     46226.742038  18503.342348
        Pennsylvania          -1655.370372     14385.139008  14477.227620
        Rhode Island           -527.540000       512.061000   6640.180320
        Vermont                -584.664589        21.390920   8553.384260
        West Virginia          2862.037853       642.286176    489.668600
South   Alabama                3033.745400      7702.353520     35.885000
        Arkansas               3853.491600      1990.592700   3589.118220
        Florida                -324.145531      6629.309060  18111.643716
        Georgia               -1370.015745      6581.333630  10362.535820
        Kentucky               3449.103000      3769.155688    910.939800
        Louisiana               515.262200      3087.268128  -2665.174600
        Mississippi            1362.403300    -15674.138698  -3732.804607
        North Carolina         8862.842902     32326.586315 -14568.535520
        South Carolina         -212.419800      -388.564933   1264.369200
        Tennessee             -4425.653900     -3192.449030    716.095100
        Virginia               2236.974300     15618.822568  14745.263620
West    Arizona                8480.622040     -1473.003196  36498.667516
        California            27666.049725     40928.970636  17503.367399
        Colorado              21287.259500       218.003140  -1447.240896
        Idaho                   302.125760     10898.465512   4459.531648
        Montana                 536.511380      1231.681940 -11231.881290
        Nevada                 2996.843000      -557.620840   1956.059556
        New Mexico             5166.104340      7297.351988  13547.555356
        Oregon                 5421.129280      2037.651066  46844.224722
        Utah                  -2021.632980      5088.716732  15373.760120
        Washington            10148.660787     17716.962270  17463.639500
        Wyoming               -1048.558120       175.398900   7384.077400

In [42]:
#margins for subtotal
df2 = df.pivot_table(index=['Region','State or Province'], columns ='Product Category', values='Profit',aggfunc='sum', margins = True)
df2

Product Category                  Furniture  Office Supplies     Technology  \
Region  State or Province
Central Illinois               20277.222916     43136.533480   64426.266614
        Indiana                12643.131611     13459.832672   10298.314629
        Iowa                   -1457.577960      9478.542350    9049.327488
        Kansas                  2999.125680      4647.956340    7353.586380
        Michigan                 894.250848     14907.553124   37239.547672
        Minnesota              -3294.794604      4448.651800   32449.994903
        Missouri               -4951.756520     14372.644292   15207.983146
        Nebraska                 952.957120      6802.814740    2501.810280
        North Dakota            2584.768800      4677.715080    1591.281800
        Oklahoma                8681.608400       466.522684   16287.939688
        South Dakota            2059.465120      2602.251300   13241.373700
        Texas                   8948.375098     39283.983044   60772.902672
        Wisconsin               4884.728504      8899.930696   26998.801480
East    Connecticut                3.825791      3592.215124    3961.067571
        Delaware                 423.498900       232.765400    -592.329660
        District of Columbia    4726.279220     14503.705800    6285.503700
        Maine                   1131.760551      3918.059580   11459.503240
        Maryland                9867.508702      5548.200896    5628.061136
        Massachusetts           7113.471195     10565.320024   25177.456894
        New Hampshire           3032.876471      2717.263440    4550.358000
        New Jersey             -7188.094954      9610.491928   22313.368300
        New York                2131.313209     30316.796462   81110.865182
        Ohio                    4879.188759     46226.742038   18503.342348
        Pennsylvania           -1655.370372     14385.139008   14477.227620
        Rhode Island            -527.540000       512.061000    6640.180320
        Vermont                 -584.664589        21.390920    8553.384260
        West Virginia           2862.037853       642.286176     489.668600
South   Alabama                 3033.745400      7702.353520      35.885000
        Arkansas                3853.491600      1990.592700    3589.118220
        Florida                 -324.145531      6629.309060   18111.643716
        Georgia                -1370.015745      6581.333630   10362.535820
        Kentucky                3449.103000      3769.155688     910.939800
        Louisiana                515.262200      3087.268128   -2665.174600
        Mississippi             1362.403300    -15674.138698   -3732.804607
        North Carolina          8862.842902     32326.586315  -14568.535520
        South Carolina          -212.419800      -388.564933    1264.369200
        Tennessee              -4425.653900     -3192.449030     716.095100
        Virginia                2236.974300     15618.822568   14745.263620
West    Arizona                 8480.622040     -1473.003196   36498.667516
        California             27666.049725     40928.970636   17503.367399
        Colorado               21287.259500       218.003140   -1447.240896
        Idaho                    302.125760     10898.465512    4459.531648
        Montana                  536.511380      1231.681940  -11231.881290
        Nevada                  2996.843000      -557.620840    1956.059556
        New Mexico              5166.104340      7297.351988   13547.555356
        Oregon                  5421.129280      2037.651066   46844.224722
        Utah                   -2021.632980      5088.716732   15373.760120
        Washington             10148.660787     17716.962270   17463.639500
        Wyoming                -1048.558120       175.398900    7384.077400
All                           177354.298188    451990.216493  683097.884742

Product Category                       All
Region  State or Province
Central Illinois              1.278400e+05
        Indiana               3.640128e+04
        Iowa                  1.707029e+04
        Kansas                1.500067e+04
        Michigan              5.304135e+04
        Minnesota             3.360385e+04
        Missouri              2.462887e+04
        Nebraska              1.025758e+04
        North Dakota          8.853766e+03
        Oklahoma              2.543607e+04
        South Dakota          1.790309e+04
        Texas                 1.090053e+05
        Wisconsin             4.078346e+04
East    Connecticut           7.557108e+03
        Delaware              6.393464e+01
        District of Columbia  2.551549e+04
        Maine                 1.650932e+04
        Maryland              2.104377e+04
        Massachusetts         4.285625e+04
        New Hampshire         1.030050e+04
        New Jersey            2.473577e+04
        New York              1.135590e+05
        Ohio                  6.960927e+04
        Pennsylvania          2.720700e+04
        Rhode Island          6.624701e+03
        Vermont               7.990111e+03
        West Virginia         3.993993e+03
South   Alabama               1.077198e+04
        Arkansas              9.433203e+03
        Florida               2.441681e+04
        Georgia               1.557385e+04
        Kentucky              8.129198e+03
        Louisiana             9.373557e+02
        Mississippi          -1.804454e+04
        North Carolina        2.662089e+04
        South Carolina        6.633845e+02
        Tennessee            -6.902008e+03
        Virginia              3.260106e+04
West    Arizona               4.350629e+04
        California            8.609839e+04
        Colorado              2.005802e+04
        Idaho                 1.566012e+04
        Montana              -9.463688e+03
        Nevada                4.395282e+03
        New Mexico            2.601101e+04
        Oregon                5.430301e+04
        Utah                  1.844084e+04
        Washington            4.532926e+04
        Wyoming               6.510918e+03
All                           1.312442e+06

In [27]:
df2.iloc[1]

Product Category
Furniture          12643.131611
Office Supplies    13459.832672
Technology         10298.314629
All                36401.278912
Name: (Central, Indiana), dtype: float64

In [31]:
df2.loc['East']['All']

State or Province
Connecticut               7557.108486
Delaware                    63.934640
District of Columbia     25515.488720
Maine                    16509.323371
Maryland                 21043.770734
Massachusetts            42856.248113
New Hampshire            10300.497911
New Jersey               24735.765274
New York                113558.974853
Ohio                     69609.273145
Pennsylvania             27206.996256
Rhode Island              6624.701320
Vermont                   7990.110591
West Virginia             3993.992629
Name: All, dtype: float64

In [37]:
df2.loc['East']["Furniture"]

State or Province
Connecticut                3.825791
Delaware                 423.498900
District of Columbia    4726.279220
Maine                   1131.760551
Maryland                9867.508702
Massachusetts           7113.471195
New Hampshire           3032.876471
New Jersey             -7188.094954
New York                2131.313209
Ohio                    4879.188759
Pennsylvania           -1655.370372
Rhode Island            -527.540000
Vermont                 -584.664589
West Virginia           2862.037853
Name: Furniture, dtype: float64

In [38]:
#df2.loc['Central'].loc["Illinois"]
#or 
df2.loc['Central','Illinois']

Product Category
Furniture           20277.222916
Office Supplies     43136.533480
Technology          64426.266614
All                127840.023010
Name: (Central, Illinois), dtype: float64

In [41]:
df3 = df.pivot_table(index=['Region','State or Province'], columns =['Product Category', 'Customer Segment'], values='Profit',aggfunc='sum', margins = all)
df3['Furniture']
# cant just plug furniture in first line of code, have to establish df and then isolate furniture

Customer Segment                  Consumer     Corporate   Home Office  \
Region  State or Province
Central Illinois               2375.435416   9315.222500  -9329.213000
        Indiana                -231.488600   3769.566540   7255.195500
        Iowa                   -419.489900   -620.427560   -417.660500
        Kansas                 2300.328040    734.539800    100.894400
        Michigan              -2435.428852  -1401.103620   2908.247180
        Minnesota              1657.286940  -5364.936940    253.274896
        Missouri                258.116500  -5955.296000    275.068080
        Nebraska                       NaN   2188.761020     60.786100
        North Dakota                   NaN     -3.488000   2588.256800
        Oklahoma               2141.265700   1888.757300   2453.762900
        South Dakota                   NaN   2673.954320   -614.489200
        Texas                  1319.221686   2309.685912   4692.523060
        Wisconsin              6724.272360  -1386.105616   1718.626800
East    Connecticut            -457.110946    766.924000    527.431600
        Delaware                423.498900           NaN           NaN
        District of Columbia   1251.759220    873.962000   2595.888000
        Maine                  2733.175262  -1848.479472  -1571.717573
        Maryland               4107.115523   3589.166166     55.090938
        Massachusetts          -522.153741   3870.083126   4719.323250
        New Hampshire          2772.627075   -808.868800   1046.739796
        New Jersey            -2358.470950  -2809.734472    842.838675
        New York               7422.566420  -3262.936949  -4020.058201
        Ohio                   -116.842678   -779.418556   5003.151070
        Pennsylvania          -4971.797376   2738.256971   1308.780348
        Rhode Island                   NaN           NaN    365.250000
        Vermont                  41.494518  -3306.013575   1958.259594
        West Virginia         -1738.819517   4679.679098     35.958672
South   Alabama                1212.613800    -65.404000  -2084.112600
        Arkansas                  9.050000  -2155.684200   6339.292400
        Florida                   2.809100  -1953.480124  -1728.716707
        Georgia                 463.833630  -2628.301819   2289.652700
        Kentucky                       NaN   3745.219000   -296.116000
        Louisiana              1407.360400  -1245.138800    326.580000
        Mississippi            1857.158600           NaN    -24.957300
        North Carolina         7601.332093    217.284780    979.555929
        South Carolina         1174.638000   -231.174800  -1028.500000
        Tennessee              -767.250400  -3178.005400   -166.250000
        Virginia               1087.364500   1453.166400   -197.477400
West    Arizona                2090.060320    164.787800   4603.561900
        California             1296.599645  14363.944300   5344.770340
        Colorado               2361.927840   6461.368260    355.516200
        Idaho                  2456.876800     89.726960           NaN
        Montana                 702.166800    -42.533040   -350.510880
        Nevada                 4358.277400   -556.250000   -805.184400
        New Mexico             1502.062200   -321.231840    166.099880
        Oregon                 4727.366800   1852.349120  -2918.420000
        Utah                   -348.342300  -1768.400520    184.093040
        Washington            11366.068757   3183.038600  -2702.203520
        Wyoming                 597.826680   -211.580000   -401.692800
All                           67436.361665  29025.449872  32697.189966

Customer Segment              Small Business
Region  State or Province
Central Illinois                17915.778000
        Indiana                  1849.858171
        Iowa                             NaN
        Kansas                   -136.636560
        Michigan                 1822.536140
        Minnesota                 159.580500
        Missouri                  470.354900
        Nebraska                -1296.590000
        North Dakota                     NaN
        Oklahoma                 2197.822500
        South Dakota                     NaN
        Texas                     626.944440
        Wisconsin               -2172.065040
East    Connecticut              -833.418863
        Delaware                         NaN
        District of Columbia        4.670000
        Maine                    1818.782334
        Maryland                 2116.136075
        Massachusetts            -953.781440
        New Hampshire              22.378400
        New Jersey              -2862.728206
        New York                 1991.741939
        Ohio                      772.298923
        Pennsylvania             -730.610315
        Rhode Island             -892.790000
        Vermont                   721.594874
        West Virginia            -114.780400
South   Alabama                  3970.648200
        Arkansas                 -339.166600
        Florida                  3355.242200
        Georgia                 -1495.200256
        Kentucky                         NaN
        Louisiana                  26.460600
        Mississippi              -469.798000
        North Carolina             64.670100
        South Carolina           -127.383000
        Tennessee                -314.148100
        Virginia                 -106.079200
West    Arizona                  1622.212020
        California               6660.735440
        Colorado                12108.447200
        Idaho                   -2244.478000
        Montana                   227.388500
        Nevada                           NaN
        New Mexico               3819.174100
        Oregon                   1759.833360
        Utah                      -88.983200
        Washington              -1698.243050
        Wyoming                 -1033.112000
All                             48195.296686